name: Deploy to Cloud Run via Cloud Build

on:
  push:
    branches:
      - main  # main ブランチに push されたときにトリガーされる

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub リポジトリの内容をクローン
      - name: Checkout code
        uses: actions/checkout@v2

      # GCP 認証設定
      - name: Set up Google Cloud authentication
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Cloud Build を実行
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml .